### PR TITLE
Patternnumber.cpp

### PR DESCRIPTION
**Pull request by chiragcode11**
Description

Error detection in c++ code.

Type of Change

change of code

Checklist

- [x]  My changes generate all writings are my own.
- [x]  My changes generate no new warnings.
- [x]  I have performed a self-review of my own writing and code.
- [x]  I have checked my entry and corrected any misspellings.
- [x]  I have confirmed my changes are not being pushed from my forked main branch.
- [x]  I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by chiragcode11** [comment]
pattern number

**Comment by abhinavcodedeveloper** [comment]
@chiragcode11 You have done it right..But you don't have to change the input...The code should be applicable for all the inputs..you have attached the screenshot for n=4...but in the code it is for all integers

**Comment by chiragcode11** [comment]
sure I will do it then @abhinavcodedeveloper

**Comment by chiragcode11** [comment]
pt2

**Comment by chiragcode11** [comment]
I have pushed the ne changes

**Comment by abhinavcodedeveloper** [comment]
Yes now it is correct

**Pull request merged**
