### PR TITLE
Python count characters #125

### PR DESCRIPTION
**Pull request by SouvikDcoder**
Hi! @reeba212 
This is a PR that resolves issue #125.
Kindly review and merge. 
Do let me know if any changes are required.

### CODE REVIEW

**Comment by SouvikDcoder** [comment]
Hi, @reeba212 any updates on the PR review?

**Comment by vaibhav-sangwan** [comment]
@SouvikDcoder please provide a screenshot of output in this PR's comment

**Comment by SouvikDcoder** [comment]
@vaibhav-sangwan PFA screenshot for the output: 
image
Do let me know if you require anything else from my end!

**Review by divya520357 — APPROVED** [review]

**Comment by SouvikDcoder** [comment]
@divya520357 @vaibhav-sangwan @reeba212 Please add label : `hacktoberfest-accepted` for hacktoberfest consideration.

**Pull request merged**
